/**
 * Generated by scripts/write-runtime-config.mjs — do not edit by hand.
 * @type {{ apiUrl: string, platform: string, buildTag: string }}
 */
window.__INKLING_RUNTIME__ = {
  apiUrl: "https://inkling-15yf.onrender.com",
  platform: "web",
  buildTag: "dev",
  vapidPublicKey: "BL7bonHBP1UdyZVg4vUUkXOgOsQo3mXT_QqZnZQv7_J0y65mDBL__VW4cvQBnG2xxW5NY9ieMzC8EA0xyrYInbs",
  nativeShell: false
};

if (window.__INKLING_RUNTIME__.apiUrl) {
  window.__EUGENEOUS_API__ = window.__INKLING_RUNTIME__.apiUrl.replace(/\/$/, "");
}
if (window.__INKLING_RUNTIME__.vapidPublicKey) {
  window.__INKLING_VAPID__ = window.__INKLING_RUNTIME__.vapidPublicKey;
}
